#ifndef ASSIGNMENTS
#define ASSIGNMENTS

enum AssingmentType {
    ASSIGN_NONE,
    ASSIGN_ASSIGN,
    ASSIGN_PIPE_ASSIGN,
    ASSIGN_AMPERSAND_ASSIGN,
    ASSIGN_MULTIPLY_ASSIGN,
    ASSIGN_DIVIDE_ASSIGN,
};

#endif
