#ifndef BUILD_IN_OPERATORS
#define BUILD_IN_OPERATORS

enum BinaryOperation {
    BINARY_NONE,
    BINARY_ADDITION,
    BINARY_SUBTRACTION,
    BINARY_DIVISION,
    BINARY_MULTIPLICATION,
    BINARY_DIFFERENT,
    BINARY_EQUALS_EQUALS,
    BINARY_GREATER,
    BINARY_LESS,
    BINARY_GREATER_OR_EQUAL,
    BINARY_LESS_OR_EQUAL,
    BINARY_BINARY_OR,
    BINARY_BINARY_AND,
    BINARY_OR,
    BINARY_AND
};

enum UnaryOperation {
    UNARY_NONE,
    UNARY_EXCLAMATION,
    UNARY_PRE_ADD_ADD,
    UNARY_AFTER_ADD_ADD,
    UNARY_PRE_MINUS_MINUS,
    UNARY_AFTER_MINUS_MINUS,
    UNARY_MINUS,
};

#endif